name: YAML2JSON
run-name: "Converting the original YAML files to JSON for the Datahub (created by ${{ github.actor }})" 
on: [push]
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Automatically triggered by a ${{ github.event_name }} event."
      - run: echo "branch = ${{ github.ref }}; repository = ${{ github.repository }}"
      - run: echo "workspace = ${{ github.workspace }}"
      - name: Check out repository code (necessary - otherwise the workspace is empty)
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: pip install tqdm
      - name: run python script
        run: |
          python ${{ github.workspace }}/scripts/test_actions.py
      - run: |
          git config user.email "valevogelmann@gmail.com"
          git config user.name "valevo"
          git add .
          git commit -m "testing this"
          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."
