name: YAML2JSON
run-name: "Converting the original YAML files to JSON for the Datahub (created by ${{ github.actor }})" 
on: [push]
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Automatically triggered by a ${{ github.event_name }} event."
      - run: echo "branch = ${{ github.ref }}; repository = ${{ github.repository }}"
      - run: echo "workspace = ${{ github.workspace }}"
      - name: List files in the repository
        run: |
          python ${{ github.workspace }}/scripts/test_actions.py
      - run: echo "🍏 This job's status is ${{ job.status }}."
