name: YAML2JSON
run-name: "Converting the original YAML files to JSON for the Datahub (created by ${{ github.actor }})" 
on: [push]
jobs:
  convert-yaml-to-json:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Automatically triggered by a ${{ github.event_name }} event."
      - run: echo "branch = ${{ github.ref }}; repository = ${{ github.repository }}"
      - run: echo "workspace = ${{ github.workspace }}"
      - name: Check out repository code (necessary - otherwise the workspace is empty)
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: running python script
        run: |
          pip install tqdm
          python ${{ github.workspace }}/scripts/pre-commit_hook.py
      - name: pushing generated files back to repo 
        run: |
          git config user.email "valevogelmann@gmail.com"
          git config user.name "valevo"
#          git add .
#          git commit -m "testing this"
#          git push
      - run: echo "🍏 This job's status is ${{ job.status }}."
